yolo_model:

  config_file:
    name: yolov3-voc-object2.cfg
  weight_file:
    name: yolov3-voc-object2_16000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - cup
      - box
      - handle
      - cylinder
      - clock
      - tape
